// Generated by CoffeeScript 1.3.1
(function() {
  var LooksGoodToMe,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  LooksGoodToMe = (function() {

    LooksGoodToMe.name = 'LooksGoodToMe';

    function LooksGoodToMe(options) {
      if (options == null) {
        options = {};
      }
      this.make_a_badge = __bind(this.make_a_badge, this);

      this.count_ones = __bind(this.count_ones, this);

      this.refresh = __bind(this.refresh, this);

      this.refresh_rate = options.refresh_rate || 5 * 60000;
      this.good = options.good || 1;
      this.better = options.better || 2;
      this.best = options.best || 3;
      this.regexes = options.regexes || [/looks good to me/ig, /lgtm/ig, /\+1/g];
      if (this.refresh_rate > 0) {
        setInterval(this.refresh, this.refresh_rate);
      }
      this.refresh();
    }

    LooksGoodToMe.prototype.refresh = function() {
      var _this = this;
      $('.lgtm_badge').remove();
      $('.pulls .listing').each(function(index, listing) {
        var pull_url, title;
        console.log("LGTM: Pull request index page.");
        title = $(listing).find('h3');
        pull_url = title.find('a').prop('href');
        return $.get(pull_url, function(response) {
          return title.prepend(_this.make_a_badge(_this.count_ones(response)));
        });
      });
      return $('#discussion_bucket').each(function(index, discussion) {
        var badge, merge_button, title;
        console.log("LGTM: Pull request show page.");
        title = $(discussion).find('.discussion-topic-title');
        merge_button = $(discussion).find('.mergeable.clean .minibutton');
        if (badge = _this.make_a_badge(_this.count_ones(discussion), 'lgtm_large')) {
          badge.clone().prependTo(title);
          return badge.clone().prependTo(merge_button);
        }
      });
    };

    LooksGoodToMe.prototype.count_ones = function(string) {
      var ones,
        _this = this;
      ones = 0;
      $('.comment-body', string).each(function(index, comment) {
        var count, regex, _i, _len, _ref, _results;
        _ref = _this.regexes;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          regex = _ref[_i];
          if (count = $(comment).text().match(regex)) {
            _results.push(ones += count.length);
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      });
      console.log("LGTM: Found " + ones + " plus ones.");
      return ones;
    };

    LooksGoodToMe.prototype.make_a_badge = function(ones, extra_classes) {
      var badge;
      if (ones == null) {
        ones = 0;
      }
      if (extra_classes == null) {
        extra_classes = '';
      }
      badge = void 0;
      if (ones > 0) {
        badge = $('<span>');
        badge.addClass("lgtm_badge " + extra_classes);
        badge.html("+" + ones);
        if (ones >= this.good && ones < this.better) {
          badge.addClass('lgtm_good');
        } else if (ones >= this.better && ones < this.best) {
          badge.addClass('lgtm_better');
        } else if (ones >= this.best) {
          badge.addClass('lgtm_best');
        } else {
          badge.addClass('lgtm_okay');
        }
      }
      return badge;
    };

    return LooksGoodToMe;

  })();

  window.looks_good_to_me = new LooksGoodToMe();

}).call(this);
