// Generated by CoffeeScript 1.3.1
(function() {
  var best, better, good, lgtm_regexes, refresh_time;

  refresh_time = 5 * 60000;

  good = 1;

  better = 2;

  best = 3;

  lgtm_regexes = [/looks good to me/ig, /lgtm/ig, /\+1/g];

  window.lgtm_refresh = function() {
    var _this = this;
    return $('.pulls .listing').each(function(index, listing) {
      var id, ones, pull_url, title;
      ones = 0;
      title = $(listing).find('h3');
      pull_url = title.find('a').prop('href');
      title.find('.lgtm_badge').remove();
      id = pull_url.split('/pull/')[1];
      return $.get(pull_url, function(response) {
        var badge;
        $('.comment-body', response).each(function(i, comment) {
          var count, regex, _i, _len, _results;
          _results = [];
          for (_i = 0, _len = lgtm_regexes.length; _i < _len; _i++) {
            regex = lgtm_regexes[_i];
            if (count = $(comment).text().match(regex)) {
              _results.push(ones += count.length);
            } else {
              _results.push(void 0);
            }
          }
          return _results;
        });
        if (ones > 0) {
          badge = $('<span>');
          badge.addClass('lgtm_badge');
          badge.html("[+" + ones + "]");
          if (ones >= good && ones < best) {
            badge.addClass('lgtm_better');
          } else if (ones >= best) {
            badge.addClass('lgtm_best');
          } else {
            badge.addClass('lgtm_good');
          }
          return title.prepend(badge);
        }
      });
    });
  };

  window.lgtm_refresh();

  setInterval(window.lgtm_refresh, refresh_time);

}).call(this);
